# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  DOCKER_IMAGE_REP: 'balangandio/migration'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: $(DOCKER_IMAGE_REP)
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'
    tags: 'latest'

- script: echo $(DOCKER_IMAGE_REP) > docker_image_rep.txt

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'docker_image_rep.txt'
    ArtifactName: 'drop'